services: 
  react:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5173:5173"
    restart: always
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    expose:
      - "8080:8080"
    restart: always
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: